sudo: false
language: rust
cache:
  cargo: true
rust:
- stable
- nightly
env:
- RUST_BACKTRACE=full
matrix:
  fast_finish: true
os:
- linux
- osx
script:
- cargo test
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --no-run --all-features;
  fi
