sudo: false
language: rust
cache:
  cargo: true
rust:
- stable
- nightly
env:
- RUST_BACKTRACE=full
matrix:
  allow_failures:
  - os: osx
    rust: nightly
  fast_finish: true
os:
- linux
- osx
script:
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo build --all-features --all-targets;
  fi
- cargo test --all
