sudo: false
language: rust
cache:
  cargo: true
rust:
- stable
- nightly
env:
- RUST_BACKTRACE=full
matrix:
  allow_failures:
  - rust: nightly
  - os: osx
  fast_finish: true
os:
- linux
- osx
script:
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo test --features bench;
  else
    cargo test;
  fi
