sudo: false
language: rust
cache:
  cargo: true
rust:
- stable
- nightly
env:
- RUST_BACKTRACE=full
matrix:
  allow_failures:
  - rust: nightly
os:
- linux
- osx
script:
- echo "TRAVIS_RUST_VERSION $TRAVIS_RUST_VERSION"
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo test --features bench;
  else
    cargo test;
  fi
