sudo: false
language: rust
cache:
  cargo: true
rust:
- stable
## Note: disabled as rustdoc compile changes to include_bytes!
## cause compile failure in 1.21 (easy to fix, but will cause failure in current stable)
## TODO re-enable after 1.21 stable release
# - nightly
env:
- RUST_BACKTRACE=full
matrix:
  allow_failures:
  - rust: nightly
os:
- linux
- osx
script:
- cargo test
