[package]
name = "glyph_brush"
version = "0.2.2"
authors = ["Alex Butler <alexheretic@gmail.com>"]
description = "Fast cached text render library using rusttype"
repository = "https://github.com/alexheretic/gfx-glyph"
keywords = ["font", "ttf", "truetype", "text"]
license = "Apache-2.0"
readme="README.md"

[dependencies]
glyph_brush_layout = { version = "0.1.1", path = "../glyph-brush-layout" }
log = "0.4"
ordered-float = "1"
rustc-hash = "1"
rusttype = { version = "0.7", features = ["gpu_cache"] }
seahash = "3"

[dev-dependencies]
env_logger = { version = "0.6", default-features = false }
lazy_static = "1"
gl = "0.11"
glutin = "0.18"
spin_sleep = "0.3"
